"""phase 1: domain schema

Revision ID: faa7edc3b48e
Revises: 64dd66ad2889
Create Date: 2026-09-07 21:15:57.567761

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "faa7edc3b48e"
down_revision: str | None = "64dd66ad2889"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "businesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("business_type", sa.String(), nullable=True),
        sa.Column("contact_phone", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column(
            "default_fulfillment_method",
            sa.Enum(
                "PICKUP",
                "DELIVERY",
                "OTHER",
                name="ck_businesses_default_fulfillment_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "default_labor_rate",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("target_contribution_margin", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("fulfillment_warning_minutes", sa.Integer(), nullable=False),
        sa.Column("shopping_horizon_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "default_labor_rate >= 0", name=op.f("ck_businesses_default_labor_rate_non_negative")
        ),
        sa.CheckConstraint(
            "fulfillment_warning_minutes > 0",
            name=op.f("ck_businesses_fulfillment_warning_minutes_positive"),
        ),
        sa.CheckConstraint(
            "shopping_horizon_days IN (3, 7)",
            name=op.f("ck_businesses_shopping_horizon_days_allowed"),
        ),
        sa.CheckConstraint(
            "target_contribution_margin IS NULL OR "
            "(target_contribution_margin >= 0 AND target_contribution_margin < 1)",
            name=op.f("ck_businesses_target_contribution_margin_range"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_businesses_owner_user_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("owner_user_id", name=op.f("uq_businesses_owner_user_id")),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("preferred_contact_method", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_customers_business_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(
        "ix_customers_business_id_is_active",
        "customers",
        ["business_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "measurement_family",
            sa.Enum(
                "WEIGHT",
                "VOLUME",
                "COUNT",
                name="ck_ingredients_measurement_family",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("canonical_unit", sa.String(), nullable=False),
        sa.Column(
            "physical_quantity",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "weighted_average_unit_cost",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("latest_purchase_unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("replacement_unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "canonical_unit IN "
            "('L', 'cup', 'each', 'fl_oz', 'g', 'kg', 'lb', 'mL', 'oz', 'tbsp', 'tsp')",
            name=op.f("ck_ingredients_canonical_unit_valid"),
        ),
        sa.CheckConstraint(
            "latest_purchase_unit_cost IS NULL OR latest_purchase_unit_cost >= 0",
            name=op.f("ck_ingredients_latest_purchase_unit_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "replacement_unit_cost IS NULL OR replacement_unit_cost >= 0",
            name=op.f("ck_ingredients_replacement_unit_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "weighted_average_unit_cost >= 0",
            name=op.f("ck_ingredients_weighted_average_unit_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_ingredients_business_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
    )
    op.create_index(
        "ix_ingredients_business_id_is_active",
        "ingredients",
        ["business_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "product_type",
            sa.Enum(
                "PRODUCED",
                "PURCHASED",
                name="ck_products_product_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "default_packaging_cost",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("can_reuse_surplus", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("default_surplus_usable_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "default_packaging_cost >= 0",
            name=op.f("ck_products_default_packaging_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "default_surplus_usable_days IS NULL OR default_surplus_usable_days > 0",
            name=op.f("ck_products_default_surplus_usable_days_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_products_business_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "ix_products_business_id_product_type_is_active",
        "products",
        ["business_id", "product_type", "is_active"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("order_number", sa.String(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "READY",
                "COMPLETED",
                "CANCELED",
                name="ck_orders_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("fulfillment_date", sa.Date(), nullable=True),
        sa.Column("fulfillment_time", sa.Time(), nullable=True),
        sa.Column(
            "fulfillment_method",
            sa.Enum(
                "PICKUP",
                "DELIVERY",
                "OTHER",
                name="ck_orders_fulfillment_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("fulfillment_details", sa.Text(), nullable=True),
        sa.Column("fulfillment_notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column(
            "subtotal", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "order_adjustment",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "manual_tax", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "final_total", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("adjustment_description", sa.String(), nullable=True),
        sa.Column("estimated_direct_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("estimated_contribution", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("estimated_contribution_margin", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "estimated_direct_cost IS NULL OR estimated_direct_cost >= 0",
            name=op.f("ck_orders_estimated_direct_cost_non_negative"),
        ),
        sa.CheckConstraint("final_total >= 0", name=op.f("ck_orders_final_total_non_negative")),
        sa.CheckConstraint("manual_tax >= 0", name=op.f("ck_orders_manual_tax_non_negative")),
        sa.CheckConstraint(
            "order_adjustment = 0 OR adjustment_description IS NOT NULL",
            name=op.f("ck_orders_adjustment_description_required"),
        ),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_orders_subtotal_non_negative")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_orders_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "business_id", "order_number", name="uq_orders_business_id_order_number"
        ),
    )
    op.create_index(
        "ix_orders_business_id_completed_at",
        "orders",
        ["business_id", "completed_at"],
        unique=False,
    )
    op.create_index(
        "ix_orders_business_id_fulfillment_date",
        "orders",
        ["business_id", "fulfillment_date"],
        unique=False,
    )
    op.create_index(
        "ix_orders_business_id_status", "orders", ["business_id", "status"], unique=False
    )
    op.create_table(
        "purchased_product_inventory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "physical_quantity",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "weighted_average_unit_cost",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("latest_purchase_unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("replacement_unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "latest_purchase_unit_cost IS NULL OR latest_purchase_unit_cost >= 0",
            name=op.f("ck_purchased_inventory_latest_purchase_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "physical_quantity >= 0",
            name=op.f("ck_purchased_product_inventory_physical_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "replacement_unit_cost IS NULL OR replacement_unit_cost >= 0",
            name=op.f("ck_purchased_inventory_replacement_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "weighted_average_unit_cost >= 0",
            name=op.f("ck_purchased_inventory_wavg_unit_cost_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_purchased_product_inventory_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchased_product_inventory_product_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchased_product_inventory")),
        sa.UniqueConstraint(
            "business_id",
            "product_id",
            name="uq_purchased_product_inventory_business_id_product_id",
        ),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_recipes_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_recipes_product_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
        sa.UniqueConstraint("business_id", "product_id", name="uq_recipes_business_id_product_id"),
    )
    op.create_table(
        "selling_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity_units", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "packaging_cost", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "packaging_cost >= 0", name=op.f("ck_selling_options_packaging_cost_non_negative")
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_selling_options_price_non_negative")),
        sa.CheckConstraint(
            "quantity_units > 0", name=op.f("ck_selling_options_quantity_units_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_selling_options_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_selling_options_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selling_options")),
    )
    op.create_table(
        "order_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "line_type",
            sa.Enum(
                "STANDARD_OPTION",
                "CUSTOM_QUANTITY",
                "CUSTOM_ITEM",
                name="ck_order_lines_line_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("selling_option_id", sa.UUID(), nullable=True),
        sa.Column("display_name_snapshot", sa.String(), nullable=False),
        sa.Column("package_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("underlying_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("charged_unit_price_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "packaging_cost_per_package_snapshot",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "packaging_cost_total_snapshot",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("price_override_reason", sa.String(), nullable=True),
        sa.Column("custom_direct_cost_estimate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("custom_active_time_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "manual_fulfillment_required", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "manual_fulfillment_satisfied", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(line_type = 'STANDARD_OPTION' AND product_id IS NOT NULL "
            "AND selling_option_id IS NOT NULL) "
            "OR (line_type = 'CUSTOM_QUANTITY' AND product_id IS NOT NULL "
            "AND selling_option_id IS NULL) "
            "OR (line_type = 'CUSTOM_ITEM' AND product_id IS NULL "
            "AND selling_option_id IS NULL)",
            name=op.f("ck_order_lines_line_type_shape"),
        ),
        sa.CheckConstraint(
            "charged_unit_price_snapshot >= 0",
            name=op.f("ck_order_lines_charged_unit_price_snapshot_non_negative"),
        ),
        sa.CheckConstraint(
            "custom_active_time_minutes IS NULL OR custom_active_time_minutes >= 0",
            name=op.f("ck_order_lines_custom_active_time_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "custom_direct_cost_estimate IS NULL OR custom_direct_cost_estimate >= 0",
            name=op.f("ck_order_lines_custom_direct_cost_estimate_non_negative"),
        ),
        sa.CheckConstraint(
            "line_subtotal >= 0", name=op.f("ck_order_lines_line_subtotal_non_negative")
        ),
        sa.CheckConstraint(
            "package_quantity > 0", name=op.f("ck_order_lines_package_quantity_positive")
        ),
        sa.CheckConstraint(
            "packaging_cost_per_package_snapshot >= 0",
            name=op.f("ck_order_lines_packaging_cost_per_package_snapshot_non_negative"),
        ),
        sa.CheckConstraint(
            "packaging_cost_total_snapshot >= 0",
            name=op.f("ck_order_lines_packaging_cost_total_snapshot_non_negative"),
        ),
        sa.CheckConstraint(
            "underlying_quantity > 0", name=op.f("ck_order_lines_underlying_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_order_lines_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_lines_order_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_lines_product_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["selling_option_id"],
            ["selling_options.id"],
            name=op.f("fk_order_lines_selling_option_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
    )
    op.create_table(
        "order_status_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "READY",
                "COMPLETED",
                "CANCELED",
                name="ck_order_status_history_from_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "READY",
                "COMPLETED",
                "CANCELED",
                name="ck_order_status_history_to_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_order_status_history_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_payments_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_payments_order_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_table(
        "recipe_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("yield_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("active_time_minutes", sa.Integer(), nullable=False),
        sa.Column("elapsed_time_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "active_time_minutes >= 0",
            name=op.f("ck_recipe_revisions_active_time_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "elapsed_time_minutes IS NULL OR elapsed_time_minutes >= active_time_minutes",
            name=op.f("ck_recipe_revisions_elapsed_gte_active"),
        ),
        sa.CheckConstraint(
            "revision_number > 0", name=op.f("ck_recipe_revisions_revision_number_positive")
        ),
        sa.CheckConstraint(
            "yield_quantity > 0", name=op.f("ck_recipe_revisions_yield_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_recipe_revisions_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_revisions_recipe_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_revisions")),
        sa.UniqueConstraint(
            "recipe_id", "revision_number", name="uq_recipe_revisions_recipe_id_revision_number"
        ),
    )
    op.create_index(
        "ix_recipe_revisions_one_current",
        "recipe_revisions",
        ["recipe_id"],
        unique=True,
        postgresql_where="is_current = true",
    )
    op.create_table(
        "production_requirements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("recipe_revision_id", sa.UUID(), nullable=True),
        sa.Column("demand_date", sa.Date(), nullable=False),
        sa.Column(
            "calculation_status",
            sa.Enum(
                "CALCULATED",
                "INCOMPLETE_RECIPE",
                name="ck_production_requirements_calculation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confirmed_demand_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "surplus_allocated_quantity",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("production_demand_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("recommended_batches", sa.Integer(), nullable=True),
        sa.Column("expected_output_quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("expected_excess_quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("estimated_active_minutes", sa.Integer(), nullable=True),
        sa.Column("estimated_elapsed_minutes", sa.Integer(), nullable=True),
        sa.Column("suggested_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_ingredient_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("estimated_labor_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "estimated_direct_production_cost", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(recipe_revision_id IS NULL AND calculation_status = 'INCOMPLETE_RECIPE') "
            "OR (recipe_revision_id IS NOT NULL AND calculation_status = 'CALCULATED')",
            name=op.f("ck_production_requirements_revision_status_match"),
        ),
        sa.CheckConstraint(
            "confirmed_demand_quantity > 0",
            name=op.f("ck_production_requirements_confirmed_demand_quantity_positive"),
        ),
        sa.CheckConstraint(
            "estimated_active_minutes IS NULL OR estimated_active_minutes >= 0",
            name=op.f("ck_prod_reqs_est_active_minutes_nonneg"),
        ),
        sa.CheckConstraint(
            "estimated_direct_production_cost IS NULL OR estimated_direct_production_cost >= 0",
            name=op.f("ck_prod_reqs_est_direct_prod_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "estimated_elapsed_minutes IS NULL OR estimated_elapsed_minutes >= 0",
            name=op.f("ck_prod_reqs_est_elapsed_minutes_nonneg"),
        ),
        sa.CheckConstraint(
            "estimated_ingredient_cost IS NULL OR estimated_ingredient_cost >= 0",
            name=op.f("ck_prod_reqs_est_ingredient_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "estimated_labor_cost IS NULL OR estimated_labor_cost >= 0",
            name=op.f("ck_production_requirements_estimated_labor_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "expected_excess_quantity IS NULL OR expected_excess_quantity >= 0",
            name=op.f("ck_prod_reqs_expected_excess_qty_nonneg"),
        ),
        sa.CheckConstraint(
            "expected_output_quantity IS NULL OR expected_output_quantity >= 0",
            name=op.f("ck_prod_reqs_expected_output_qty_nonneg"),
        ),
        sa.CheckConstraint(
            "production_demand_quantity >= 0",
            name=op.f("ck_prod_reqs_production_demand_qty_nonneg"),
        ),
        sa.CheckConstraint(
            "recommended_batches IS NULL OR recommended_batches >= 0",
            name=op.f("ck_production_requirements_recommended_batches_non_negative"),
        ),
        sa.CheckConstraint(
            "surplus_allocated_quantity >= 0",
            name=op.f("ck_prod_reqs_surplus_allocated_qty_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_production_requirements_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_production_requirements_product_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_revision_id"],
            ["recipe_revisions.id"],
            name=op.f("fk_production_requirements_recipe_revision_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_requirements")),
    )
    op.create_index(
        "ix_production_requirements_business_id_demand_date",
        "production_requirements",
        ["business_id", "demand_date"],
        unique=False,
    )
    op.create_index(
        "ix_production_requirements_business_id_product_id_demand_date",
        "production_requirements",
        ["business_id", "product_id", "demand_date"],
        unique=False,
    )
    op.create_index(
        "ix_production_requirements_unique_calculated",
        "production_requirements",
        ["business_id", "product_id", "recipe_revision_id", "demand_date"],
        unique=True,
        postgresql_where="recipe_revision_id IS NOT NULL",
    )
    op.create_index(
        "ix_production_requirements_unique_incomplete",
        "production_requirements",
        ["business_id", "product_id", "demand_date"],
        unique=True,
        postgresql_where="recipe_revision_id IS NULL",
    )
    op.create_table(
        "purchased_product_inventory_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "INITIAL_BALANCE",
                "RESTOCK",
                "ORDER_FULFILLMENT",
                "MANUAL_ADJUSTMENT",
                name="ck_purchased_product_inventory_transactions_transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quantity_change", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("supplier_text", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("order_line_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_cost IS NULL OR total_cost >= 0",
            name=op.f("ck_purchased_inventory_txn_total_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "unit_cost IS NULL OR unit_cost >= 0",
            name=op.f("ck_purchased_inventory_txn_unit_cost_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_purchased_product_inventory_transactions_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_purchased_product_inventory_transactions_order_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_purchased_product_inventory_transactions_order_line_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchased_product_inventory_transactions_product_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchased_product_inventory_transactions")),
    )
    op.create_table(
        "purchased_product_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_purchased_product_reservations_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_purchased_product_reservations_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_purchased_product_reservations_order_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_purchased_product_reservations_order_line_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchased_product_reservations_product_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchased_product_reservations")),
    )
    op.create_index(
        "ix_purchased_product_reservations_business_id_product_id",
        "purchased_product_reservations",
        ["business_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "recipe_revision_ingredients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("recipe_revision_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.CheckConstraint(
            "unit IN ('L', 'cup', 'each', 'fl_oz', 'g', 'kg', 'lb', 'mL', 'oz', 'tbsp', 'tsp')",
            name=op.f("ck_recipe_revision_ingredients_unit_valid"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_recipe_revision_ingredients_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_recipe_revision_ingredients_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_recipe_revision_ingredients_ingredient_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_revision_id"],
            ["recipe_revisions.id"],
            name=op.f("fk_recipe_revision_ingredients_recipe_revision_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_revision_ingredients")),
    )
    op.create_table(
        "ingredient_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("production_requirement_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("quantity_canonical", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_canonical > 0",
            name=op.f("ck_ingredient_reservations_quantity_canonical_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_ingredient_reservations_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_ingredient_reservations_ingredient_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["production_requirement_id"],
            ["production_requirements.id"],
            name=op.f("fk_ingredient_reservations_production_requirement_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredient_reservations")),
        sa.UniqueConstraint(
            "production_requirement_id",
            "ingredient_id",
            name="uq_ingredient_reservations_requirement_id_ingredient_id",
        ),
    )
    op.create_index(
        "ix_ingredient_reservations_business_id_ingredient_id",
        "ingredient_reservations",
        ["business_id", "ingredient_id"],
        unique=False,
    )
    op.create_table(
        "production_ingredient_requirements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("production_requirement_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("required_quantity_canonical", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("estimated_unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("estimated_total_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.CheckConstraint(
            "estimated_total_cost IS NULL OR estimated_total_cost >= 0",
            name=op.f("ck_prod_ingredient_reqs_est_total_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "estimated_unit_cost IS NULL OR estimated_unit_cost >= 0",
            name=op.f("ck_prod_ingredient_reqs_est_unit_cost_nonneg"),
        ),
        sa.CheckConstraint(
            "required_quantity_canonical > 0",
            name=op.f("ck_prod_ingredient_reqs_required_qty_canonical_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_production_ingredient_requirements_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_production_ingredient_requirements_ingredient_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["production_requirement_id"],
            ["production_requirements.id"],
            name=op.f("fk_production_ingredient_requirements_production_requirement_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_ingredient_requirements")),
        sa.UniqueConstraint(
            "production_requirement_id",
            "ingredient_id",
            name="uq_prod_ingredient_reqs_requirement_id_ingredient_id",
        ),
    )
    op.create_table(
        "production_requirement_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("production_requirement_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("demand_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.CheckConstraint(
            "demand_quantity > 0",
            name=op.f("ck_production_requirement_orders_demand_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_production_requirement_orders_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_production_requirement_orders_order_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_production_requirement_orders_order_line_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["production_requirement_id"],
            ["production_requirements.id"],
            name=op.f("fk_production_requirement_orders_production_requirement_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_requirement_orders")),
    )
    op.create_table(
        "production_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("source_production_requirement_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("recipe_revision_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PRODUCTION",
                "COMPLETED",
                "CANCELED",
                name="ck_production_runs_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("planned_batches", sa.Integer(), nullable=False),
        sa.Column("planned_output_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("actual_output_quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("recipe_yield_snapshot", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("active_minutes_per_batch_snapshot", sa.Integer(), nullable=False),
        sa.Column("elapsed_minutes_per_batch_snapshot", sa.Integer(), nullable=True),
        sa.Column("labor_rate_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("estimated_ingredient_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("estimated_labor_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "estimated_total_production_cost", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("actual_ingredient_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("actual_labor_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("actual_total_production_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "active_minutes_per_batch_snapshot >= 0",
            name=op.f("ck_prod_runs_active_min_per_batch_snapshot_nonneg"),
        ),
        sa.CheckConstraint(
            "actual_ingredient_cost IS NULL OR actual_ingredient_cost >= 0",
            name=op.f("ck_production_runs_actual_ingredient_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_labor_cost IS NULL OR actual_labor_cost >= 0",
            name=op.f("ck_production_runs_actual_labor_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_output_quantity IS NULL OR actual_output_quantity >= 0",
            name=op.f("ck_production_runs_actual_output_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_total_production_cost IS NULL OR actual_total_production_cost >= 0",
            name=op.f("ck_production_runs_actual_total_production_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "elapsed_minutes_per_batch_snapshot IS NULL "
            "OR elapsed_minutes_per_batch_snapshot >= active_minutes_per_batch_snapshot",
            name=op.f("ck_production_runs_elapsed_gte_active_snapshot"),
        ),
        sa.CheckConstraint(
            "estimated_ingredient_cost >= 0",
            name=op.f("ck_production_runs_estimated_ingredient_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_labor_cost >= 0",
            name=op.f("ck_production_runs_estimated_labor_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_total_production_cost >= 0",
            name=op.f("ck_production_runs_estimated_total_production_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "labor_rate_snapshot >= 0",
            name=op.f("ck_production_runs_labor_rate_snapshot_non_negative"),
        ),
        sa.CheckConstraint(
            "planned_batches > 0", name=op.f("ck_production_runs_planned_batches_positive")
        ),
        sa.CheckConstraint(
            "planned_output_quantity > 0",
            name=op.f("ck_production_runs_planned_output_quantity_positive"),
        ),
        sa.CheckConstraint(
            "recipe_yield_snapshot > 0",
            name=op.f("ck_production_runs_recipe_yield_snapshot_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_production_runs_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_production_runs_product_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_revision_id"],
            ["recipe_revisions.id"],
            name=op.f("fk_production_runs_recipe_revision_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["source_production_requirement_id"],
            ["production_requirements.id"],
            name=op.f("fk_production_runs_source_production_requirement_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_runs")),
    )
    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "INITIAL_BALANCE",
                "RESTOCK",
                "PRODUCTION_CONSUMPTION",
                "MANUAL_ADJUSTMENT",
                name="ck_inventory_transactions_transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quantity_change", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("supplier_text", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("production_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_cost IS NULL OR total_cost >= 0",
            name=op.f("ck_inventory_transactions_total_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_cost IS NULL OR unit_cost >= 0",
            name=op.f("ck_inventory_transactions_unit_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_inventory_transactions_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_inventory_transactions_ingredient_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["production_run_id"],
            ["production_runs.id"],
            name=op.f("fk_inventory_transactions_production_run_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transactions")),
    )
    op.create_index(
        "ix_inventory_transactions_business_id_ingredient_id_created_at",
        "inventory_transactions",
        ["business_id", "ingredient_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "production_run_ingredients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("production_run_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("planned_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("actual_quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "weighted_average_unit_cost_snapshot", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column(
            "replacement_unit_cost_snapshot", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column("actual_unit_cost_basis", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("actual_total_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.CheckConstraint(
            "actual_quantity IS NULL OR actual_quantity >= 0",
            name=op.f("ck_production_run_ingredients_actual_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_total_cost IS NULL OR actual_total_cost >= 0",
            name=op.f("ck_production_run_ingredients_actual_total_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_unit_cost_basis IS NULL OR actual_unit_cost_basis >= 0",
            name=op.f("ck_prod_run_ingr_actual_cost_basis_nonneg"),
        ),
        sa.CheckConstraint(
            "planned_quantity > 0",
            name=op.f("ck_production_run_ingredients_planned_quantity_positive"),
        ),
        sa.CheckConstraint(
            "replacement_unit_cost_snapshot IS NULL OR replacement_unit_cost_snapshot >= 0",
            name=op.f("ck_prod_run_ingr_replacement_cost_snapshot_nonneg"),
        ),
        sa.CheckConstraint(
            "weighted_average_unit_cost_snapshot >= 0",
            name=op.f("ck_prod_run_ingr_wavg_unit_cost_snapshot_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_production_run_ingredients_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_production_run_ingredients_ingredient_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["production_run_id"],
            ["production_runs.id"],
            name=op.f("fk_production_run_ingredients_production_run_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_run_ingredients")),
    )
    op.create_table(
        "production_run_order_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("production_run_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_production_run_order_allocations_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_production_run_order_allocations_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_production_run_order_allocations_order_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_production_run_order_allocations_order_line_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["production_run_id"],
            ["production_runs.id"],
            name=op.f("fk_production_run_order_allocations_production_run_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_run_order_allocations")),
    )
    op.create_table(
        "surplus_inventory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("source_production_run_id", sa.UUID(), nullable=True),
        sa.Column("physical_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_cost_basis", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("produced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usable_through_date", sa.Date(), nullable=True),
        sa.Column("is_reusable", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "physical_quantity >= 0",
            name=op.f("ck_surplus_inventory_physical_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_cost_basis >= 0", name=op.f("ck_surplus_inventory_unit_cost_basis_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_surplus_inventory_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_surplus_inventory_product_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["source_production_run_id"],
            ["production_runs.id"],
            name=op.f("fk_surplus_inventory_source_production_run_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surplus_inventory")),
    )
    op.create_index(
        "ix_surplus_inventory_business_id_product_id_usable_through_date",
        "surplus_inventory",
        ["business_id", "product_id", "usable_through_date"],
        unique=False,
    )
    op.create_table(
        "order_cost_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=True),
        sa.Column(
            "cost_type",
            sa.Enum(
                "PRODUCTION",
                "SURPLUS",
                "PURCHASED_GOOD",
                "PACKAGING",
                "CUSTOM_DIRECT",
                name="ck_order_cost_allocations_cost_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("production_run_order_allocation_id", sa.UUID(), nullable=True),
        sa.Column("surplus_inventory_id", sa.UUID(), nullable=True),
        sa.Column("purchased_inventory_transaction_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cost_type = 'PRODUCTION' AND production_run_order_allocation_id IS NOT NULL "
            "AND surplus_inventory_id IS NULL AND purchased_inventory_transaction_id IS NULL) "
            "OR (cost_type = 'SURPLUS' AND surplus_inventory_id IS NOT NULL "
            "AND production_run_order_allocation_id IS NULL "
            "AND purchased_inventory_transaction_id IS NULL) "
            "OR (cost_type = 'PURCHASED_GOOD' AND purchased_inventory_transaction_id IS NOT NULL "
            "AND production_run_order_allocation_id IS NULL AND surplus_inventory_id IS NULL) "
            "OR (cost_type IN ('PACKAGING', 'CUSTOM_DIRECT') "
            "AND production_run_order_allocation_id IS NULL AND surplus_inventory_id IS NULL "
            "AND purchased_inventory_transaction_id IS NULL)",
            name=op.f("ck_order_cost_allocations_source_exclusivity"),
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_order_cost_allocations_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_order_cost_allocations_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_cost_allocations_order_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_order_cost_allocations_order_line_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["production_run_order_allocation_id"],
            ["production_run_order_allocations.id"],
            name=op.f("fk_order_cost_allocations_production_run_order_allocation_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["purchased_inventory_transaction_id"],
            ["purchased_product_inventory_transactions.id"],
            name=op.f("fk_order_cost_allocations_purchased_inventory_transaction_id"),
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["surplus_inventory_id"],
            ["surplus_inventory.id"],
            name=op.f("fk_order_cost_allocations_surplus_inventory_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_cost_allocations")),
    )
    op.create_table(
        "surplus_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("surplus_inventory_id", sa.UUID(), nullable=False),
        sa.Column("production_requirement_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_surplus_allocations_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_surplus_allocations_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_surplus_allocations_order_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_surplus_allocations_order_line_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["production_requirement_id"],
            ["production_requirements.id"],
            name=op.f("fk_surplus_allocations_production_requirement_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["surplus_inventory_id"],
            ["surplus_inventory.id"],
            name=op.f("fk_surplus_allocations_surplus_inventory_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surplus_allocations")),
    )
    op.create_table(
        "surplus_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("surplus_inventory_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "PRODUCTION_OUTPUT",
                "ORDER_FULFILLMENT",
                "MANUAL_ADJUSTMENT",
                name="ck_surplus_transactions_transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quantity_change", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("order_line_id", sa.UUID(), nullable=True),
        sa.Column("production_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_surplus_transactions_business_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_surplus_transactions_order_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_surplus_transactions_order_line_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["production_run_id"],
            ["production_runs.id"],
            name=op.f("fk_surplus_transactions_production_run_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["surplus_inventory_id"],
            ["surplus_inventory.id"],
            name=op.f("fk_surplus_transactions_surplus_inventory_id"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surplus_transactions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surplus_transactions")
    op.drop_table("surplus_allocations")
    op.drop_table("order_cost_allocations")
    op.drop_index(
        "ix_surplus_inventory_business_id_product_id_usable_through_date",
        table_name="surplus_inventory",
    )
    op.drop_table("surplus_inventory")
    op.drop_table("production_run_order_allocations")
    op.drop_table("production_run_ingredients")
    op.drop_index(
        "ix_inventory_transactions_business_id_ingredient_id_created_at",
        table_name="inventory_transactions",
    )
    op.drop_table("inventory_transactions")
    op.drop_table("production_runs")
    op.drop_table("production_requirement_orders")
    op.drop_table("production_ingredient_requirements")
    op.drop_index(
        "ix_ingredient_reservations_business_id_ingredient_id", table_name="ingredient_reservations"
    )
    op.drop_table("ingredient_reservations")
    op.drop_table("recipe_revision_ingredients")
    op.drop_index(
        "ix_purchased_product_reservations_business_id_product_id",
        table_name="purchased_product_reservations",
    )
    op.drop_table("purchased_product_reservations")
    op.drop_table("purchased_product_inventory_transactions")
    op.drop_index(
        "ix_production_requirements_unique_incomplete",
        table_name="production_requirements",
        postgresql_where="recipe_revision_id IS NULL",
    )
    op.drop_index(
        "ix_production_requirements_unique_calculated",
        table_name="production_requirements",
        postgresql_where="recipe_revision_id IS NOT NULL",
    )
    op.drop_index(
        "ix_production_requirements_business_id_product_id_demand_date",
        table_name="production_requirements",
    )
    op.drop_index(
        "ix_production_requirements_business_id_demand_date", table_name="production_requirements"
    )
    op.drop_table("production_requirements")
    op.drop_index(
        "ix_recipe_revisions_one_current",
        table_name="recipe_revisions",
        postgresql_where="is_current = true",
    )
    op.drop_table("recipe_revisions")
    op.drop_table("payments")
    op.drop_table("order_status_history")
    op.drop_table("order_lines")
    op.drop_table("selling_options")
    op.drop_table("recipes")
    op.drop_table("purchased_product_inventory")
    op.drop_index("ix_orders_business_id_status", table_name="orders")
    op.drop_index("ix_orders_business_id_fulfillment_date", table_name="orders")
    op.drop_index("ix_orders_business_id_completed_at", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_products_business_id_product_type_is_active", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_ingredients_business_id_is_active", table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index("ix_customers_business_id_is_active", table_name="customers")
    op.drop_table("customers")
    op.drop_table("businesses")
    op.drop_table("users")
    # ### end Alembic commands ###
